In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [7]:
arr.dtype

dtype('int32')

In [8]:
np.zeros((1, 20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [9]:
np.zeros((1, 20), int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((3, 2), 10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [15]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [19]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
array[0, 1]

2

In [21]:
array[0]

array([1, 2, 3])

In [23]:
array[:, 0]

array([1, 4, 7])

In [26]:
array[:, 2]

array([3, 6, 9])

In [49]:
array[1:, 0] = 3
array

array([[1, 1, 3],
       [3, 1, 6],
       [3, 1, 9]])

In [29]:
array[0] = 3
array

array([[3, 3, 3],
       [3, 5, 6],
       [3, 8, 9]])

In [30]:
array[0:3:, 0:2] = 1
array

array([[1, 1, 3],
       [1, 1, 6],
       [1, 1, 9]])

In [52]:
print(array.shape)

(3, 3)


In [53]:
print(array.size)

9


In [36]:
print(array.max())

9


In [37]:
print(array.min())

1


In [40]:
print(array.ndim)

2


In [41]:
print(array.max(axis=0))

[1 1 9]


In [46]:
ar = np.resize(array, (5, 5))
ar

array([[1, 1, 3, 1, 1],
       [6, 1, 1, 9, 1],
       [1, 3, 1, 1, 6],
       [1, 1, 9, 1, 1],
       [3, 1, 1, 6, 1]])

In [48]:
ar = np.reshape(array, (1, 9))
ar

array([[1, 1, 3, 1, 1, 6, 1, 1, 9]])

In [57]:
a =np.array([1,2,3])
b = np.array([4,5,6])

c=a+b
print(c)

[5 7 9]


In [59]:
number = np.arange(0,101)
number
max = max(number)
max

100

In [68]:
array = np.array([[1, 2, 3, 4, 5], [6,7,8,9,10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [67]:
array[0:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])